version: '3'
services: 
    frontend:
        container_name: project-manager-frontend
        restart: always
        build: ./client
        volumes:
            - .:/client
            # - /client/node_modules
        ports: 
            - '8085:80'
        links:
            - backend
    backend:
        container_name: project-manager-backend
        build: .
        ports:
            - '5000:5000'
        links:
            - mongo
    mongo:
        container_name: mongopm
        image: mongo
        volumes:
            - .:/var/lib/mongo/data
        ports:
            - '27017:27017'